# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Only issues that requires info from the op
onlyLabels:
  - "Status: Feedback needed"

# Issues with these labels will never be considered stale
exemptLabels:
  - "Priority: Critical"
  - "Priority: Security"
  - "Status: Confirmed"
  - "Status: Complete"
  - "Status: Review Needed"
  - "Status: On Hold"
  - "Status: In Progress"
  - security

# Label to use when marking an issue as stale
staleLabel: "Status: Stale"

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity and seems to be missing some essential information. It will
  be closed if no further activity occurs. Thank you for your contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
# closeComment: false

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Limit to only `issues` or `pulls`
only: issues
