name: Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

jobs:
  tests:
    name: "Python ${{ matrix.name }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.9', os: ubuntu-latest, tox: py39}
          - {name: Windows, python: '3.9', os: windows-latest, tox: py39}
          - {name: Mac, python: '3.9', os: macos-latest, tox: py39}
          - {name: '3.8', python: '3.8', os: ubuntu-latest, tox: py38}
          - {name: '3.7', python: '3.7', os: ubuntu-latest, tox: py37}
          - {name: '3.6', python: '3.6', os: ubuntu-latest, tox: py36}
          - {name: 'PyPy', python: pypy3, os: ubuntu-latest, tox: pypy3}

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: ${{ matrix.python }}
      - name: update pip
        run: |
          set -xe
          python -VV
          python -m site
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - name: get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('setup.py') }}|${{ hashFiles('requirements/*.txt') }}
      - run: pip install tox
      - name: "Run tox targets for ${{ matrix.python }}"
        run: tox -e ${{ matrix.tox }}
