# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

name: Python CI Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

jobs:
  tests:
    name: "Python ${{ matrix.name }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.9', os: ubuntu-latest, tox: py39}
          - {name: Windows, python: '3.9', os: windows-latest, tox: py39}
          # ToDo: There are errors on Mac, but I don't know why: Connection timeout or reset
          # - {name: Mac, python: '3.9', os: macos-latest, tox: py39}
          - {name: '3.11', python: '3.11', os: ubuntu-latest, tox: py311}
          - {name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310}
          - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39}
          - {name: '3.8', python: '3.8', os: ubuntu-latest, tox: py38}
          - {name: '3.7', python: '3.7', os: ubuntu-latest, tox: py37}
          - {name: 'PyPy 3.9', python: pypy3.9, os: ubuntu-latest, tox: pypy39}

    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-python@v4"
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip' # caching pip dependencies

      - name: Install tox and any other packages
        run: pip install tox

      - name: "Run tox targets for ${{ matrix.python }}"
        run: tox -e ${{ matrix.tox }}
